### ISSUE TITLE
Windows 64 version

### ISSUE THREAD

**Issue by perdigao1** [maxxxzdn/clifford-group-equivariant-cnns#1]
This is a very interesting CNN implementation. Unfortunately JAX does not support CUDA in windows, but pytorch can. I would be interested to try a pytorch version of this, please.

Thank you
L

**Comment by maxxxzdn** [comment]
Hey, we don't really plan to port it to PyTorch. If you are interested in Euclidean group + implicit steerable kernels, you can look at my previous work: https://github.com/maxxxzdn/implicit-steerable-kernels, this one is PyTorch native. 

Btw, you can probably use Google Colab to run it, they have jax preinstalled.

**Comment by maxxxzdn** [comment]
Hey, we don't really plan to port it to PyTorch. If you are interested in Euclidean group + implicit steerable kernels, you can look at my previous work: https://github.com/maxxxzdn/implicit-steerable-kernels, this one is PyTorch native. 

Btw, you can probably use Google Colab to run it, they have jax preinstalled.
