### ISSUE TITLE
Shape mismatch in computing loss function

### ISSUE THREAD

**Issue by 49takashi** [maxxxzdn/clifford-group-equivariant-cnns#2]
Hi, 

I built an environment and generated dataset following the README. When I run the maxwell2d experiment using the provided command
`python experiment.py --experiment maxwell2d --model resnet --metric -1 1 1 --time_history 32 --time_future 32 --num_data 512 --batch_size 16 --norm 0 --hidden_channels 13`
 for the standard resnet, I got the following error. Could you advise me of how to fix this issue?

> Traceback (most recent call last):
  File "/home/tmaruyama/projects/geometric-transformer-local/clifford-group-equivariant-cnns/experiment.py", line 298, in <module>
    main(args)
  File "/home/projects/clifford-group-equivariant-cnns/experiment.py", line 267, in main
    _ = train_and_evaluate(
  File "/home/projects/clifford-group-equivariant-cnns/training/common.py", line 141, in train_and_evaluate
    state, metrics = train_step(state, inputs, targets)
  File "/home/projects/clifford-group-equivariant-cnns/training/common.py", line 83, in train_step
    (_, metrics), grads = gradient_fn(state.params, inputs, targets)
  File "/home/projects/clifford-group-equivariant-cnns/training/common.py", line 79, in loss_fn
    loss, metrics = compute_losses(inputs=outputs, targets=targets)
  File "/home/projects/clifford-group-equivariant-cnns/training/losses.py", line 57, in compute_losses_maxwell2d
    inputs.shape == targets.shape
AssertionError: inputs.shape = (16, 32, 32, 32, 32, 8), targets.shape = (16, 32, 32, 32, 8)

The command for CS-Resnet on the other hand worked without observing any errors. I believe this has nothing to do with an argument `num_data`, but to be sincere I cannot be 100% sure since the data description in [Maxwell 2D+1 (spacetime)](https://github.com/maxxxzdn/clifford-group-equivariant-cnns/blob/main/datasets/data/maxwell2d/datagen/README.md) says the final dataset comprises 8192 training simulation while the paper says the final dataset comprises 2048 simulations.

Thank you very much in advance for your time taken for the issue.

**Comment by maxxxzdn** [comment]
Hey, thanks for pioneering the testing, and apologies for the bugs that managed to slip.

I fixed the bug. It basically didn't create a channel dimension instead of time (which is a grid dimension in this case), so some weird broadcasting took place instead, and the error appeared. Should work now.

Please let me know if it works.

P.S. concerning the data, we had generated 8192 trajectories indeed, you can see it in Fig.5, plot 3.

**Comment by 49takashi** [comment]
It worked! Thanks for fixing the bugs!
